<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        State::insert([        
            ['name'  =>  '[Nation Wide]', 'short_name' =>  'nostate', 'country_id' => 226],
            ['name'  =>  'Alabama', 'short_name' =>  'AL', 'country_id' => 226],
            ['name'  =>  'Alaska', 'short_name' =>  'AK', 'country_id' => 226],
            ['name'  =>  'American Samoa', 'short_name' =>  'AS', 'country_id' => 226],
            ['name'  =>  'Arizona', 'short_name' =>  'AZ', 'country_id' => 226],
            ['name'  =>  'Arkansas', 'short_name' =>  'AR', 'country_id' => 226],
            ['name'  =>  'California', 'short_name' =>  'CA', 'country_id' => 226],
            ['name'  =>  'Colorado', 'short_name' =>  'CO', 'country_id' => 226],
            ['name'  =>  'Connecticut', 'short_name' =>  'CT', 'country_id' => 226],
            ['name'  =>  'Delaware', 'short_name' =>  'DE', 'country_id' => 226],
            ['name'  =>  'District of Columbia', 'short_name' =>  'DC', 'country_id' => 226],
            ['name'  =>  'Florida', 'short_name' =>  'FL', 'country_id' => 226],
            ['name'  =>  'Georgia', 'short_name' =>  'GA', 'country_id' => 226],
            ['name'  =>  'Guam', 'short_name' =>  'GU', 'country_id' => 226],
            ['name'  =>  'Hawaii', 'short_name' =>  'HI', 'country_id' => 226],
            ['name'  =>  'Idaho', 'short_name' =>  'ID', 'country_id' => 226],
            ['name'  =>  'Illinois', 'short_name' =>  'IL', 'country_id' => 226],
            ['name'  =>  'Indiana', 'short_name' =>  'IN', 'country_id' => 226],
            ['name'  =>  'Iowa', 'short_name' =>  'IA', 'country_id' => 226],
            ['name'  =>  'Kansas', 'short_name' =>  'KS', 'country_id' => 226],
            ['name'  =>  'Kentucky', 'short_name' =>  'KY', 'country_id' => 226],
            ['name'  =>  'Louisiana', 'short_name' =>  'LA', 'country_id' => 226],
            ['name'  =>  'Maine', 'short_name' =>  'ME', 'country_id' => 226],
            ['name'  =>  'Marshall Islands', 'short_name' =>  'MH', 'country_id' => 226],
            ['name'  =>  'Maryland', 'short_name' =>  'MD', 'country_id' => 226],
            ['name'  =>  'Massachusetts', 'short_name' =>  'MA', 'country_id' => 226],
            ['name'  =>  'Michigan', 'short_name' =>  'MI', 'country_id' => 226],
            ['name'  =>  'Minnesota', 'short_name' =>  'MN', 'country_id' => 226],
            ['name'  =>  'Mississippi', 'short_name' =>  'MS', 'country_id' => 226],
            ['name'  =>  'Missouri', 'short_name' =>  'MO', 'country_id' => 226],
            ['name'  =>  'Montana', 'short_name' =>  'MT', 'country_id' => 226],
            ['name'  =>  'Nebraska', 'short_name' =>  'NE', 'country_id' => 226],
            ['name'  =>  'Nevada', 'short_name' =>  'NV', 'country_id' => 226],
            ['name'  =>  'New Hampshire', 'short_name' =>  'NH', 'country_id' => 226],
            ['name'  =>  'New Jersey', 'short_name' =>  'NJ', 'country_id' => 226],
            ['name'  =>  'New Mexico', 'short_name' =>  'NM', 'country_id' => 226],
            ['name'  =>  'New York', 'short_name' =>  'NY', 'country_id' => 226],
            ['name'  =>  'North Carolina', 'short_name' =>  'NC', 'country_id' => 226],
            ['name'  =>  'North Dakota', 'short_name' =>  'ND', 'country_id' => 226],
            ['name'  =>  'Northern Mariana Islands', 'short_name' =>  'MP', 'country_id' => 226],
            ['name'  =>  'Ohio', 'short_name' =>  'OH', 'country_id' => 226],
            ['name'  =>  'Oklahoma', 'short_name' =>  'OK', 'country_id' => 226],
            ['name'  =>  'Oregon', 'short_name' =>  'OR', 'country_id' => 226],
            ['name'  =>  'Palau', 'short_name' =>  'PW', 'country_id' => 226],
            ['name'  =>  'Pennsylvania', 'short_name' =>  'PA', 'country_id' => 226],
            ['name'  =>  'Puerto Rico', 'short_name' =>  'PR', 'country_id' => 226],
            ['name'  =>  'Rhode Island', 'short_name' =>  'RI', 'country_id' => 226],
            ['name'  =>  'South Carolina', 'short_name' =>  'SC', 'country_id' => 226],
            ['name'  =>  'South Dakota', 'short_name' =>  'SD', 'country_id' => 226],
            ['name'  =>  'Tennessee', 'short_name' =>  'TN', 'country_id' => 226],
            ['name'  =>  'Texas', 'short_name' =>  'TX', 'country_id' => 226],
            ['name'  =>  'Utah', 'short_name' =>  'UT', 'country_id' => 226],
            ['name'  =>  'Vermont', 'short_name' =>  'VT', 'country_id' => 226],
            ['name'  =>  'Virgin Islands', 'short_name' =>  'VI', 'country_id' => 226],
            ['name'  =>  'Virginia', 'short_name' =>  'VA', 'country_id' => 226],
            ['name'  =>  'Washington', 'short_name' =>  'WA', 'country_id' => 226],
            ['name'  =>  'West Virginia', 'short_name' =>  'WV', 'country_id' => 226],
            ['name'  =>  'Wisconsin', 'short_name' =>  'WI', 'country_id' => 226],
            ['name'  =>  'Wyoming', 'short_name' =>  'WY', 'country_id' => 226],
            ['name'  =>  '[Nation Wide]', 'short_name' =>  'nostate', 'country_id' => 38],
            ['name'  =>  'Alberta', 'short_name' =>  'AB', 'country_id' => 38],
            ['name'  =>  'British Columbia', 'short_name' =>  'BC', 'country_id' => 38],
            ['name'  =>  'Manitoba', 'short_name' =>  'MB', 'country_id' => 38],
            ['name'  =>  'New Brunswick', 'short_name' =>  'NB', 'country_id' => 38],
            ['name'  =>  'Newfoundland and Labrador', 'short_name' =>  'NL', 'country_id' => 38],
            ['name'  =>  'Northwest Territories', 'short_name' =>  'NT', 'country_id' => 38],
            ['name'  =>  'Nova Scotia', 'short_name' =>  'NS', 'country_id' => 38],
            ['name'  =>  'Nunavut', 'short_name' =>  'NU', 'country_id' => 38],
            ['name'  =>  'Ontario', 'short_name' =>  'ON', 'country_id' => 38],
            ['name'  =>  'Prince Edward Island', 'short_name' =>  'PE', 'country_id' => 38],
            ['name'  =>  'Quebec', 'short_name' =>  'QC', 'country_id' => 38],
            ['name'  =>  'Saskatchewan', 'short_name' =>  'SK', 'country_id' => 38],
            ['name'  =>  'Yukon Territory', 'short_name' =>  'YT', 'country_id' => 38],
            ['name'  =>  'Andaman and Nicobar Islands', 'short_name' =>  'AN', 'country_id' => 98],
            ['name'  =>  'Andhra Pradesh', 'short_name' =>  'AP', 'country_id' => 98],
            ['name'  =>  'Arunachal Pradesh', 'short_name' =>  'AR', 'country_id' => 98],
            ['name'  =>  'Assam', 'short_name' =>  'AS', 'country_id' => 98],
            ['name'  =>  'Bihar', 'short_name' =>  'BR', 'country_id' => 98],
            ['name'  =>  'Chandigarh', 'short_name' =>  'CH', 'country_id' => 98],
            ['name'  =>  'Chhattisgarh', 'short_name' =>  'CT', 'country_id' => 98],
            ['name'  =>  'Dadra and Nagar Haveli', 'short_name' =>  'DN', 'country_id' => 98],
            ['name'  =>  'Daman and Diu', 'short_name' =>  'DD', 'country_id' => 98],
            ['name'  =>  'Delhi', 'short_name' =>  'DL', 'country_id' => 98],
            ['name'  =>  'Goa', 'short_name' =>  'GA', 'country_id' => 98],
            ['name'  =>  'Gujarat', 'short_name' =>  'GJ', 'country_id' => 98],
            ['name'  =>  'Haryana', 'short_name' =>  'HR', 'country_id' => 98],
            ['name'  =>  'Himachal Pradesh', 'short_name' =>  'HP', 'country_id' => 98],
            ['name'  =>  'Jammu and Kashmir', 'short_name' =>  'JK', 'country_id' => 98],
            ['name'  =>  'Jharkhand', 'short_name' =>  'JH', 'country_id' => 98],
            ['name'  =>  'Karnataka', 'short_name' =>  'KA', 'country_id' => 98],
            ['name'  =>  'Kerala', 'short_name' =>  'KL', 'country_id' => 98],
            ['name'  =>  'Lakshadweep', 'short_name' =>  'LD', 'country_id' => 98],
            ['name'  =>  'Madhya Pradesh', 'short_name' =>  'MP', 'country_id' => 98],
            ['name'  =>  'Maharashtra', 'short_name' =>  'MH', 'country_id' => 98],
            ['name'  =>  'Manipur', 'short_name' =>  'MN', 'country_id' => 98],
            ['name'  =>  'Meghalaya', 'short_name' =>  'ML', 'country_id' => 98],
            ['name'  =>  'Mizoram', 'short_name' =>  'MZ', 'country_id' => 98],
            ['name'  =>  'Nagaland', 'short_name' =>  'NL', 'country_id' => 98],
            ['name'  =>  'Odisha', 'short_name' =>  'OR', 'country_id' => 98],
            ['name'  =>  'Puducherry', 'short_name' =>  'PY', 'country_id' => 98],
            ['name'  =>  'Punjab', 'short_name' =>  'PB', 'country_id' => 98],
            ['name'  =>  'Rajasthan', 'short_name' =>  'RJ', 'country_id' => 98],
            ['name'  =>  'Sikkim', 'short_name' =>  'SK', 'country_id' => 98],
            ['name'  =>  'Tamil Nadu', 'short_name' =>  'TN', 'country_id' => 98],
            ['name'  =>  'Telangana', 'short_name' =>  'TG', 'country_id' => 98],
            ['name'  =>  'Tripura', 'short_name' =>  'TR', 'country_id' => 98],
            ['name'  =>  'Uttar Pradesh', 'short_name' =>  'UP', 'country_id' => 98],
            ['name'  =>  'Uttarakhand', 'short_name' =>  'UT', 'country_id' => 98],
            ['name'  =>  'West Bengal', 'short_name' =>  'WB', 'country_id' =>  98]
        ]);

    }
}
